spring:
    # profiles:
    #     active:
    #     - dev
    datasource:        
        url: jdbc:mysql://localhost:3306/karthik
        username: root
        password: root
    jpa:
        hibernate:
         ddl-auto: update
        show-sql: true

ereview:
    password: '{cipher}fed5a66750f631813a6d644c47d7adea5219fa1b843d41b674ea3d81139a4121'
    username: karthik
    query: select  manager_flag from rating e where empName = ?1 limit 1
  
